source 'https://rubygems.org'
gem 'asciidoctor', '1.5.1'
gem 'asciidoctor-diagram', '1.3.0.preview.1'
gem 'asciidoctor-fopub', github: 'hnakamur/asciidoctor-fopub', branch: 'japanese'
gem 'filewatcher'
